blog/urls.py
from django.conf.urls import patterns, url
from blog.views import ListArticles

urlpatterns = patterns(
    'blog.views',
    url(r'^$', ListArticles.as_view(), name="blog_index"),
    url(r'^(?P<page>\d+)$', ListArticles.as_view(), name="blog_index"),
    url(r'^article/(?P<id>\d+)-(?P<slug>[a-z0-9\-]+)$', 'view_article', name="blog_article"),
    url(r'^article/(?P<id>\d+)-(?P<slug>[a-z0-9\-]+)/(?P<page>\d+)$', 'view_article', name="blog_article"),
)

home/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

urlpatterns = patterns(
    'home.views',
    url(r'^$', TemplateView.as_view(template_name='home/index.html'), name="home_index")
)

naleck/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', include('home.urls', app_name='home', namespace='home')),
    url(r'^blog/', include('blog.urls', app_name='blog', namespace='blog'))
]

blog/models.py
from django.db import models


class Article(models.Model):
    """Article Model"""

    title = models.CharField(max_length=256, verbose_name='Titre')
    author = models.CharField(max_length=100, verbose_name='Auteur')
    content = models.TextField(verbose_name='Contenu')
    date = models.DateTimeField(auto_now_add=True, auto_now=False, verbose_name='Publié le')
    slug = models.SlugField(max_length=100)
    visible = models.BooleanField(default=True, verbose_name='Visibilité')
    enable_comments = models.BooleanField(default=True, verbose_name='Commentaires')
    category = models.ForeignKey('Category', verbose_name='Catégorie')

    class Meta:
        verbose_name = 'article'
        verbose_name_plural = 'articles'

    def __str__(self):
        return self.title

    def get_nb_comments(self):
        return Comment.objects.filter(article=self).count()


class Category(models.Model):
    """Categories model"""

    name = models.CharField(max_length=120, verbose_name='Nom')

    class Meta:
        verbose_name = 'catégorie'
        verbose_name_plural = 'catégories'

    def __str__(self):
        return self.name


class Comment(models.Model):
    """Comments model"""

    author = models.CharField(max_length=50, verbose_name='Auteur')
    email = models.EmailField(verbose_name='Adresse email')
    content = models.TextField(verbose_name='Commentaire')
    date = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey('Article')

    class Meta:
        verbose_name = 'commentaire'
        verbose_name_plural = 'commentaires'

home/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms
from blog.models import Comment


class AddCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('article', )

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Article, Comment
from django.views.generic import ListView
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage
from blog.forms import AddCommentForm


class ListArticles(ListView):
    """Generic view - shows last articles"""

    model = Article
    context_object_name = 'articles'
    template_name = 'blog/index.html'
    paginate_by = 3
    queryset = Article.objects.filter(visible=True).order_by('-date')


def view_article(request, id, slug, page=1):
    article = get_object_or_404(Article, id=id, slug=slug)
    comment_list = Comment.objects.filter(article=article).order_by('-date')
    pg = Paginator(comment_list, 8)

    if request.method == 'POST':
        form = AddCommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = article
            comment.save()

            return redirect(reverse('blog:blog_article', args=(id, slug, )) + '#comment' + str(comment.pk))
    else:
        form = AddCommentForm()

    try:
        comments = pg.page(page)
    except EmptyPage:
        comments = pg.page(pg.num_pages)

    context = {
        'article': article,
        'form': form,
        'comments': comments
    }

    return render(request, 'blog/article_view.html', context)

home/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/article_view.html
{% extends "blog/blog.html" %}
{% block title %}| {{ article.title }} {% endblock %}

{% block content %}
    <section class="container">
        <h1>{{ article.title }}</h1>

        <div class="info">
            par {{ article.author }} - {{ article.date|date:'d/m/Y à H:i' }} - dans la catégorie "<em>{{ article.category.name }}</em>"
        </div>

        <div class="blog_text">
            {{ article.content|safe }}
        </div>
    </section>

    {% if article.enable_comments %}
        <section class="container">
            <h1>Ajouter un commentaire</h1>
            <div class="comment-form">
               <form action="" method="post">
                   {% csrf_token %}
                   <table>
                       {{ form.as_table }}
                   </table>

                   <p><input type="submit" value="Commenter" /></p>
                </form>
            </div>

            <h1 id="comments">Commentaires {% if comments > 0 %}({{ comments.count }}) {% endif %}</h1>

            {% for comment in comments %}
                <div class="comment" id="comment{{ comment.pk }}">
                    <blockquote>
                        <div class="text-comment">
                            {{ comment.content|linebreaks }}
                        </div>

                        <div class="info-comment">
                            Par <strong>{{ comment.author }}</strong> le {{ comment.date|date:'d/m/Y à H:i' }}
                        </div>
                    </blockquote>
                </div>
            {% empty %}
                <p>Aucun commentaire.</p>
            {% endfor %}

            <div class="pagination">
                {% if comments.has_previous %}
                   <a href="{% url 'blog:blog_article' article.id article.slug comments.previous_page_number %}">&laquo;</a>
                {% endif %}

                Page {{ comments.number }} sur {{ comments.paginator.num_pages }}

                {% if comments.has_next %}
                    <a href="{% url 'blog:blog_article' article.id article.slug comments.next_page_number %}">&raquo;</a>
                {% endif %}
            </div>
        </section>
    {% endif %}
{% endblock %}

blog/templates/blog/blog.html
{% extends "base.html" %}
{% block name_title %} Blog {% endblock %}
{% block spe_css %}
    <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.7/styles/monokai_sublime.min.css">
{% endblock %}

{% block spe_js %}
    <script src="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.7/highlight.min.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script>
        $(document).ready(function() {
          $('pre code').each(function(i, block) {
            hljs.highlightBlock(block);
          });
        });
    </script>
{% endblock %}

blog/templates/blog/index.html
{% extends "blog/blog.html" %}
{% block title %}| Blog {% endblock %}

{% block content %}
    {% for article in articles %}
        <section class="container">
            <h1><a href="{% url 'blog:blog_article' article.id article.slug %}">{{ article.title }}</a></h1>
            <div class="info">
                par {{ article.author }} - {{ article.date|date:'d/m/Y à H:i' }} - dans la catégorie "<em>{{ article.category.name }}</em>"
            </div>

            <div class="blog_text">
                {{ article.content|truncatewords_html:60|safe }}
            </div>

            <div class="more">
                <a href="{% url 'blog:blog_article' article.id article.slug %}">Lire la suite</a>
            </div>

            {% if article.enable_comments %}
                <div class="comments">
                    <a href="{% url 'blog:blog_article' article.id article.slug %}#comments">
                        {% if article.get_nb_comments == 0 %}
                            Aucun
                        {% else %}
                            {{ article.get_nb_comments }}
                        {% endif %}
                        commentaire{% if article.get_nb_comments > 1 %}s{% endif %}
                    </a>
                </div>
            {% endif %}
        </section>
    {% empty %}
        <section class="container">
            Aucun article.
        </section>
    {% endfor %}

    {% include "pagination.html" with list=page_obj view='blog:blog_index' %}
{% endblock %}

home/templates/home/index.html
{% extends "base.html" %}
{% block title %}| Accueil {% endblock %}

{% block content %}
    <section class="container">
        <div class="text">
            Je m’appelle <strong>Fayçal Kamel</strong>  <em>- Naleck -</em>, j’ai 18 ans et je suis étudiant en classe préparatoire à l’Ecole Nationale Polytechnique d’Alger. <br /><br />
            Je suis passionné par les nouvelles technologies depuis mon plus jeune âge, et surtout par l’informatique (programmation, hardware, …) mais aussi par l’aéronotique (contrôle aérien, pilotage). <br /> <br />
            Ceci est mon site personnel où je publie divers articles sur différents sujets : études, informatique, jeux-vidéos… <br /> <br />
        </div>

        <div class="more">
            <a href="{% url 'blog:blog_index' %}">Consulter mon blog</a>
        </div>
    </section>
{% endblock %}

templates/base.html
{% load static %}
{% load naleck_extras %}
<html>
    <head>
        <!--[if lt IE 9]>
        <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <title>
            Fayçal Kamel - Naleck
            {% block title %}

            {% endblock %}
        </title>
        <meta charset="utf-8" />
        <link rel="stylesheet" href="{% static 'css/webkitfont.css' %}">
        <link rel="stylesheet" href="{% static 'css/grid.css' %}">
        <link rel="stylesheet" href="{% static 'css/reset.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        {% block spe_css %}{% endblock %}
    </head>
    <body>
        <div class="main-container">
            <nav class="grid-100">
                <a href="{% url 'home:home_index' %}"><div id="minlogo" class="grid-20"></div></a>
                <div class="grid-80 ib">
                    <ul>
                        <li><a href="{% url 'home:home_index' %}" {% nav_active request 'home' %}>Accueil</a></li>
                        <li><a href="{% url 'blog:blog_index' %}" {% nav_active request 'blog' %}>Blog</a></li>
                    </ul>
                </div>
            </nav>

            <div class="grid-container">
                <header></header>
                <div id="name">
                    {% block name_title %}
                        Fayçal Kamel
                    {% endblock %}
                </div>

                <main>
                    <div class="grid-100">
                        {% block content %}

                        {% endblock %}
                    </div>
                </main>

                <footer>
                    <ul>
                        <li><a href="https://twitter.com/Naleck_" class="twitter"></a></li>
                    </ul>
                </footer>
            </div>
        </div>

        {% block spe_js %}

        {% endblock %}
    </body>
</html>

templates/pagination.html
<div class="pagination">
    {% if list.has_previous %}
       <a href="{% url view list.previous_page_number %}">&laquo;</a>
    {% endif %}

    Page {{ list.number }} sur {{ list.paginator.num_pages }}

    {% if list.has_next %}
        <a href="{% url view list.next_page_number %}">&raquo;</a>
    {% endif %}
</div>